name: WorldTimer
main: org.fatecrafters.plugins.WorldTime
version: 1.2
author: Slayr288
website: http://Fatecrafters.org
description: Set time limits in a world.
commands:
  worldtimer:
    description: Main commands.
    usage: /wt help
    aliases: [wt]
permissions:
  worldtimer.*:
    description: All permissions.
    default: false
    children:
      worldtimer.reload: true
      worldtimer.bypass: true 
  worldtimer.reload:
    default: op
  worldtimer.bypass:
    default: false